export const preferencesKey = 'note.boostio.co:preferences'
export const storageDataListKey = 'note.boostio.co:storageDataList'
export const generalStatusKey = 'note.boostio.co:generalStatusKey'
export const previewStyleKey = 'note.boostio.co:previewStyleKey'
export const introDataKey = 'note.boostio.co:introDataKey'
