declare module 'remark-emoji'
declare module 'remark-math'
declare module 'rehype-raw'
declare module 'rehype-sanitize'
declare module 'rehype-react'
declare module 'rehype-katex'
declare module 'hastscript'
