declare module 'remark-rehype'
declare module 'rehype-raw'
declare module 'rehype-sanitize'
declare module 'rehype-react'
declare module 'hast-util-sanitize/lib/github.json'
declare module 'hast-util-to-text'
declare module 'hastscript'
