# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'

target 'BoostNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for BoostNote

  target 'BoostNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoostNoteUITests' do
    # Pods for testing
  end

end
