export interface Backer {
  name: string
  twitterUserName?: string
}

export const backers: Backer[] = [
  { name: 'smyleeface', twitterUserName: 'smyleeface' },
  { name: 'Marco Friso', twitterUserName: 'friso_marco' },
  { name: 'themantis' },
  { name: 'Anthony Engelstad', twitterUserName: 'anton0' },
  { name: 'Jeremy Russell' },
  { name: 'Ray' },
  { name: 'jericodelfinado', twitterUserName: 'jericodelfinado' },
  { name: 'toda', twitterUserName: 'martin_tosovsky' },
  { name: 'Jakub' },
  { name: 'Dominik Galler', twitterUserName: 'dominik_galler' },
  { name: 'ParaFlacx', twitterUserName: 'paraflacx' },
  { name: 'TobseF', twitterUserName: 'TobseF' },
  { name: 'Burger Julian' },
  { name: 'Potzenhotz' },
  { name: 'Narol' },
  { name: '奥村昌生' },
  { name: 'Dan C' },
  { name: 'ilan' },
  {
    name: 'Carlos Alberto Hurtado Sánchez',
    twitterUserName: 'CarlosH13100542',
  },
  { name: 'KTGoldwolf' },
  { name: 'ystar', twitterUserName: 'ystar_kr' },
  { name: 'Maggie Blair' },
  { name: 'Vishallan Govan' },
  { name: 'Sondra Perrot', twitterUserName: 'sondrap9' },
  { name: '1run9' },
  { name: 'take8' },
  { name: 'raniantheone' },
  { name: 'Felipe Teixeira Moraes' },
  { name: 'hoeni', twitterUserName: 'hoenix' },
  { name: 'Robert' },
  { name: 'noramyao3', twitterUserName: 'noramyao3' },
  { name: 'DrayDorx', twitterUserName: 'DrayDorx' },
  { name: 'Yann' },
  { name: 'Valentin Dimitrov' },
  { name: 'matejuh', twitterUserName: 'matejuh' },
  { name: 'decoch', twitterUserName: 'decoch718' },
  { name: '"Awesome Cakes" Carlson' },
  { name: 'lord powerwalker' },
  { name: 'jonjongrim', twitterUserName: 'jonjongrim' },
  { name: 'Yass!' },
  { name: 'Alexandru Nedel' },
  { name: 'sceptiQ' },
  { name: 'Chris Schuld', twitterUserName: 'cbschuld' },
  { name: 'fanliye' },
  { name: 'Sam Thacker', twitterUserName: 'codedeeply' },
  { name: 'warvolin' },
  { name: 'Tony W', twitterUserName: 'awfgiohge' },
  { name: 'Henrik Aasted', twitterUserName: 'haasted' },
  { name: 'roottool', twitterUserName: 'roottool' },
  { name: 'Hayley Roberts', twitterUserName: 'astrohayley' },
  { name: 'frozenfroze' },
  { name: 'RenegadeOutcast' },
  { name: 'Jake Kiley', twitterUserName: 'jake_kiley' },
  { name: 'Lawrence Fritts' },
  { name: 'Tadgh' },
  { name: 'AwaNoodle' },
  { name: 'CDL', twitterUserName: 'CodingLamb' },
  { name: 'devtanc', twitterUserName: 'devtanc' },
  { name: 'André Hollstein' },
  { name: 'Zyrca' },
  { name: 'Solariz.de', twitterUserName: 'solariz' },
  { name: 'Daniel de Paula' },
  { name: 'joelbcastillo', twitterUserName: 'joelbcastillo' },
  { name: 'Ale Song' },
  { name: 'ballweera', twitterUserName: 'ballweera' },
  { name: 'Lloyd Rowe', twitterUserName: 'lr00429' },
  { name: 'Charlie Mikels' },
  { name: 'Ricardo Antonio', twitterUserName: 'rantoniodev' },
  { name: 'wgkoro', twitterUserName: 'wg_koro' },
  { name: 'ezuall' },
  { name: 'Kribbstar' },
  { name: 'Oldie55', twitterUserName: 'DietscheOliver' },
  { name: 'MrTimeey', twitterUserName: 'tim_siegler' },
  { name: 'Eralmione', twitterUserName: 'MirbachEric' },
  { name: 'anasazy' },
  { name: 'Lukas Runge' },
  { name: 'Kool_Just_In_Time' },
  { name: 'tamasviktor', twitterUserName: 'tamasviktor' },
  { name: 'Marcel S' },
  { name: 'memyselfandy', twitterUserName: 'memyselfandy' },
  { name: 'jagijagijag1', twitterUserName: 'jagijagijag1' },
  { name: 'Jonathan Montgomery', twitterUserName: 'Darkspark77024' },
  { name: 'askjarv', twitterUserName: 'askjarv' },
  { name: 'Katsu' },
  { name: 'lulezi', twitterUserName: 'lulezi' },
  { name: 'Fabian Baumeister', twitterUserName: 'BaumeisterFa' },
  { name: 'Joe YAMAHATA' },
  { name: 'Russell Folk', twitterUserName: 'russellfolk' },
  { name: 'Bastien Queste', twitterUserName: 'DrQueste' },
  { name: 'Paul N. Ehler', twitterUserName: 'paulnehler' },
  { name: 'Uwe Sauerbrei', twitterUserName: 'Ostfale' },
  { name: 'Giampaolo Frello', twitterUserName: 'giampi2602' },
  { name: 'Konstantin Boyandin', twitterUserName: 'temmokan' },
  { name: 'Daly', twitterUserName: 'Seamus_eDaly' },
  { name: 'Amit', twitterUserName: 'amitagni' },
  { name: 'Dr. Michael Noll-Hussong', twitterUserName: 'MNollHussong' },
  { name: 'aXe1', twitterUserName: '_aXe1' },
  { name: 'Tom Stevens', twitterUserName: 'webbson_' },
  { name: 'sunghlin', twitterUserName: 'sunghlin' },
  { name: 'Tudor Plugaru', twitterUserName: 'PlugaruTudor' },
  { name: 'Turaj Pilehvar' },
  { name: 'Shosh', twitterUserName: 'shoshievass' },
  { name: 'Nicholas Browning' },
  { name: 'wojtekk' },
  { name: 'Anthony Rojas', twitterUserName: 'anthony_r0' },
  { name: 'James Mackin', twitterUserName: 'sketch720' },
  { name: 'Wilson Fan', twitterUserName: 'yuero' },
  { name: 'Christian Dimas', twitterUserName: 'kenanchristian' },
  { name: 'kcnickerson', twitterUserName: 'kcnickerson' },
  { name: 'Rijo Simon', twitterUserName: 'rijosimon' },
  { name: 'Rick P' },
  { name: 'daisuke7', twitterUserName: 'daisuke7' },
  { name: 'Silverbreeze', twitterUserName: 'silverbreeze' },
  { name: 'Happy Support #10432' },
  { name: 'Tomoaki Fukuzumi', twitterUserName: 'Orugah02' },
  { name: 'MikeA' },
]
