export type FormattingTool =
  | 'header1'
  | 'header2'
  | 'header3'
  | 'header4'
  | 'header5'
  | 'header6'
  | 'bold'
  | 'italic'
  | 'quote'
  | 'code'
  | 'bulletedList'
  | 'numberedList'
  | 'taskList'
  | 'link'
  | 'codefence'
