export const preferencesKey = 'boosthub:preferences'
export const searchKey = 'boosthub:search'
export const searchHistoryKey = 'boosthub:search:history'
export const sidebarCollapseKey = 'boosthub:sidebar'
export const mobilePreferencesKey = 'boosthub:mobile:preferences'
